let users = [
    {
        name: "Alexis Ferrer",
        username: "alexis.ferrer",
        company: "ECPay",
        count: 0,
        isCreated: true,
    },
    {
        name: "Angel Rose Dela Cruz",
        username: "angel.vargas",
        company: "ECPay",
        count: 0,
        isCreated: true,
    },
    {
        name: "Jerald Sibulangcao",
        username: "jerald.sibulangcao",
        company: "ECPay",
        count: 0,
        isCreated: true,
    },
    {
        name: "Judith Dacut",
        username: "judith.dacut",
        company: "ECPay",
        count: 0,
        isCreated: true,
    },
    {
        name: "Michael Sam Mendoza",
        username: "michael.mendoza",
        company: "ECPay",
        count: 0,
        isCreated: true,
    },
    {
        name: "Apollo Administrator",
        username: "apollo_admin",
        company: "Apollo",
        count: 0,
        isCreated: true,
    },
    {
        name: "Charina Castillano",
        username: "charina.castillano",
        company: "Apollo",
        count: 0,
        isCreated: false,
    },
    {
        name: "Cloudine Rosales",
        username: "cbrosales",
        company: "Apollo",
        count: 0,
        isCreated: true,
    },
    {
        name: "Jennikar Magalong",
        username: "jennikardm",
        company: "Apollo",
        count: 0,
        isCreated: false,
    },
    {
        name: "Jerome Encinares",
        username: "encinares",
        company: "Apollo",
        count: 0,
        isCreated: false,
    },
    {
        name: "Jonathan Roque",
        username: "jonroque",
        company: "Apollo",
        count: 0,
        isCreated: false,
    },
    {
        name: "Jonvic Tuatis",
        username: "jonvic",
        company: "Apollo",
        count: 0,
        isCreated: true,
    },
    {
        name: "Junel Manlangit",
        username: "Jumanlangit",
        company: "Apollo",
        count: 0,
        isCreated: true,
    },
    {
        name: "Mark Junel Clorado",
        username: "mjclorado",
        company: "Apollo",
        count: 0,
        isCreated: true,
    },
    {
        name: "Neil Dan Chu",
        username: "Neil",
        company: "Apollo",
        count: 0,
        isCreated: false,
    },
    {
        name: "Renier Jay Molina",
        username: "renierjay",
        company: "Apollo",
        count: 0,
        isCreated: true,
    },
    {
        name: "Ronan Ray Maala",
        username: "rmaala",
        company: "Apollo",
        count: 0,
        isCreated: true,
    },
    {
        name: "Thomas Castillo",
        username: "tcastillo",
        company: "Apollo",
        count: 0,
        isCreated: true,
    },
]

export default users